Add support for GitHub Actions in travis-haskell
TokTok/ci-tools pull request #24
Opened 2021-01-02 19:05 UTC by robinlinden

The name `travis-haskell` is a bit unfortunate, but this makes it usable from GitHub Actions as well. I could also copy-paste the script and give it a name like `ci-haskell`. Renaming the script would break a lot of our CI due to usage like this: https://github.com/TokTok/c-toxcore/blob/master/.travis/cmake-linux#L11-L14.

2021-01-02 19:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TokTok/ci-tools?pullRequest=24) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/TokTok/ci-tools?pullRequest=24) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: robinlinden<br/>:x: restyled-commits<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TokTok/ci-tools?pullRequest=24) it.</sub>

2021-01-05 19:31 UTC, krobelus reviewed
I'm not really involved but renaming the script and keeping a link for compatibility seems fine.

2021-01-05 19:31 UTC, krobelus commented on bin/travis-haskell
> +    python3 -c 'import sys, json; print(json.loads(sys.stdin.read())["tag_name"])')
```suggestion
    python3 -c 'import sys, json; print(json.load(sys.stdin)["tag_name"])')
```

2021-01-05 20:55 UTC, robinlinden commented on bin/travis-haskell
> +    python3 -c 'import sys, json; print(json.loads(sys.stdin.read())["tag_name"])')
The reason I didn't is because of usage like the one I linked in the PR. It downloads only this one script and executes it, not the entire repo. Turns out it doesn't matter anyway since toktok uses too many minutes and can't use Travis at all anymore, so I'll rename it without a care for backwards-compat. :P

I didn't review the changes the bots made too closely since they're enforced as a rule on the repo. :x Will apply your change to the reformat commit though, thank you! :D

2021-01-05 21:08 UTC, krobelus commented on bin/travis-haskell
> +    python3 -c 'import sys, json; print(json.loads(sys.stdin.read())["tag_name"])')
Right, essentially all OSS projects need to switch away from Travis anyway (https://news.ycombinator.com/item?id=25338983), might as well remove all Travis-specific code and references to Travis in the readme.

2021-12-03 01:09 UTC, iphydf requested changes
Let's rename things from travis to ci. Nothing will break, because travis left us. We'll also need to replace the packaging and uploading of binaries with a github action.

2021-12-03 01:10 UTC, iphydf approved these changes

2022-02-13 19:03 UTC, iphydf commented
We're doing haskell differently on GH actions.

2022-02-13 19:03 UTC, closed without merging